# -*- coding: utf-8 -*-
"""Student Info.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pB7p-Q_59GAFKVLDCuJh7MFHPAJrc594
"""

import pandas as pd 
df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRBJnebvMnlTNzQGPPEsU8BKIXKcV_T5Wq4h6zPzTpw3dzIbjQWR8tIoqhq16Ys8mzLs_MwPUTY-3ja/pub?gid=633075172&single=true&output=csv") 
df

df.describe()

from sklearn.preprocessing import LabelEncoder
df["gender_encoded"] = LabelEncoder().fit_transform( df["gender"] )
df

from sklearn.preprocessing import LabelEncoder
df["result_encoded"] = LabelEncoder().fit_transform( df["final_result"] )
df

from sklearn.preprocessing import LabelEncoder
df["educationLevel_encoded"] = LabelEncoder().fit_transform( df["highest_education"] )
df

import seaborn as sns
import matplotlib.pyplot as plt

sns.distplot(df["studied_credits"])

df_input = df[["gender_encoded", "educationLevel_encoded", "studied_credits"]]

df_input

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth=4)

classifier.fit(df_input, df["result_encoded"])

from sklearn.tree import plot_tree
fig, ax = plt.subplots(figsize=(100, 100))  # size of the output
plot_tree( classifier )
plt.show()

fig, ax = plt.subplots(figsize=(100, 100))  # whatever size you want
plot_tree( classifier, ax=ax, feature_names=df_input.columns,
                    class_names=['distinction', 'fail','pass','withdrawn'], filled=True )
plt.show()

cleanup_nums = {"highest_education" : { "Post Graduate Qualification":4,"HE Qualification":3, "A Level or Equivalent":2, "Lower Than A Level":1, "No Formal quals":0}}
df_copy = df.copy()

df_copy

df_copy.replace(cleanup_nums, inplace=True)

df_copy

df_input_copy = df_copy[["gender_encoded", "highest_education", "studied_credits"]]
df_input_copy

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth=5)

classifier.fit(df_input_copy, df_copy["result_encoded"])

from sklearn.tree import plot_tree
fig, ax = plt.subplots(figsize=(100, 100))  # size of the output
plot_tree( classifier )
plt.show()

fig, ax = plt.subplots(figsize=(300, 300))  # whatever size you want
plot_tree( classifier, ax=ax, feature_names=df_input_copy.columns,
                    class_names=['distinction', 'fail','pass','withdrawn'], filled=True )
plt.show()